selenium-hub:
  restart: always
  image: selenium/hub:latest
  ports:
    - "4445:4444"
    

selenium-chrome-1:
  restart: always
  image: selenium/node-chrome
  ports:
    - "5000:5000"
  stdin_open: true
  links:
    - selenium-hub:hub

selenium-firefox:
  restart: always
  image: selenium/node-firefox
  ports:
    - "6000:6000"
  links:
    - selenium-hub:hub
